[package]
name = "evo_bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.0", features = ["dynamic_linking"] }
bevy_prototype_lyon = "0.12.0"
fastrand = "2.1.0"
rand = "0.8.5"
